### ISSUE TITLE
Canopydb v0.2.4 fails to compile with smallvec 2.0.0-alpha.12 (breaking API changes in SmallVec)

### ISSUE THREAD

**Issue by den59k** [arthurprs/canopydb#23]
Hi! I’m trying to use canopydb v0.2.4 in a fresh project and it fails to compile due to an incompatibility with the latest SmallVec pre-release.

### Summary

`canopydb = "0.2.4"` depends on:

```toml
smallvec = { version = "2.0.0-alpha.11" }
```

However, Cargo’s semver rules treat `"2.0.0-alpha.11"` as a *minimum* version (`>= alpha.11 and < 2.0.0`), so Cargo automatically pulls the latest prerelease: **2.0.0-alpha.12**.

SmallVec 2.0.0-alpha.12 removed the methods:

* `insert_from_slice`
* `SmallVec::from_slice`

which canopydb uses.

This causes compilation to fail.

### Error

```
error[E0599]: no method named `insert_from_slice` found for mutable reference `&mut SmallVec<freelist::Range, 29>`
 --> ...\canopydb-0.2.4\src\freelist.rs:490:20

error[E0599]: no function or associated item named `from_slice` found for struct `SmallVec<u8, 256>`
 --> ...\canopydb-0.2.4\src\tree.rs:927:44
```

### Cause

The upstream SmallVec crate introduced breaking API changes in `2.0.0-alpha.12`.
Because canopydb depends on `"2.0.0-alpha.11"` (non-exact version), Cargo upgrades automatically.

### How to reproduce

```
cargo new test-db
# Add dependency:
# canopydb = "0.2.4"
cargo build
```

### Suggested fix

Two possible approaches:

1. **Pin SmallVec exactly**
   Change the dependency to:

   ```toml
   smallvec = { version = "=2.0.0-alpha.11" }
   ```

   or update canopydb to use the new SmallVec API (replace `insert_from_slice` with `insert_from_slice_copy`, `from_slice` with `from_slice_copy`).

2. **Update code to be compatible with alpha.12 and future 2.0.0 releases.**

### Additional notes

Right now it’s impossible for users to override the version cleanly because Cargo does not allow patching a crate to a different version from crates.io unless the source is changed (git/local path).

Thanks!
